import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
const shabnamFont = localFont({
  src: [
    {
      path: "../../public/fonts/shabnam/Shabnam-Medium.woff2",
      weight: "normal",
    },
    {
      path: "../../public/fonts/shabnam/Shabnam-Bold.woff2",
      weight: "bold",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body className={shabnamFont.className}>{children}</body>
    </html>
  );
}
