import AosInit from "@/utils/aos";
import ScrollToTop from "@/utils/Scroll-to-top";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "../styles/globals.css";
// const shabnamFont = localFont({
//   src: [
//     {
//       path: "../../public/fonts/shabnam/Shabnam-Medium.woff2",
//       weight: "normal",
//     },
//     {
//       path: "../../public/fonts/shabnam/Shabnam-Bold.woff2",
//       weight: "bold",
//     },
//   ],
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/Lovepik_com-450039165- Coffee vector.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body
      // className={shabnamFont.className}
      >
        <AosInit />
        {children}
        <ScrollToTop />
        <ToastContainer
          position="top-center"
          theme="light"
          hideProgressBar={true}
          closeButton={false}
          pauseOnFocusLoss={false}
          pauseOnHover={false}
        />
      </body>
    </html>
  );
}
