import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import AosInit from "@/utils/aos";
const shabnamFont = localFont({
  src: "../../public/fonts/shabnam/Shabnam-Medium.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/Lovepik_com-450039165- Coffee vector.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body className={shabnamFont.className}>
        <AosInit />
        {children}
      </body>
    </html>
  );
}
